dtrack-url: https://dtrack.example.com
dtrack-apikey: changeit
opa-url: http://localhost:8181
watch-bundle: dtapac
finding-policy-path: /dtapac/finding
violation-policy-path: /dtapac/violation
log-level: debug
log-json: true
dry-run: true
# filter-tag:
#   - production
#   - staging